title: Core Interaction Spring 2024
url: "http://core-interaction.example.com"
collections_dir: _content
includes_dir: _layouts/_includes

collections:
  lab_projects:
    output: true
    permalink: /projects/:title.html
  lab_workshops:
    output: true
    permalink: /workshops/:title.html
  studio_projects:
    output: true
    permalink: /projects/:title.html
  studio_workshops:
    output: true
    permalink: /workshops/:title.html

defaults:
  - 
    scope:
      type: lab_projects
    values:
      layout: post
  - 
    scope:
      type: lab_workshops
    values:
      layout: post
  - 
    scope:
      type: studio_projects
    values:
      layout: post
  - 
    scope:
      type: studio_workshops
    values:
      layout: post

markdown: kramdown
highlighter: rouge
plugins: 
  - jekyll-feed
  - jekyll-last-modified-at